name: Actions Workflow
on: 
  push:
    branches:
      - master
      - "feature/*"  #!................................... note_0003
      - "feature/**" #!................................... note_0004
      - "!feature/ignoreC" #!............................. branches-ignore と同じ
    branches-ignore:
      - 'feature/ignoreD'
    tags:
      - v1.*
    paths:
      - "**.js"
      - "!ignore01.js"
    paths-ignore:
      - "ignore02.js"
jobs:
  run-github-action:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls -Altr
          echo $GITHUB_SHA #! ............................ clone 対象の CommitID (HEAD)
          echo $GITHUB_REPOSITORY #!...................... 本ワークフローファイルが格納されているリポジトリ
          echo $GITHUB_WORKSPACE #!....................... GitHub-hosted server におけるワークスペース
          # git clone git@github:$GITHUB_REPOSITORY
          # git checkout git@github:$GITHUB_SHA
      - name: Checkout
        uses: actions/checkout@v1
      - name: List Files After Checkout
        run: |
          pwd
          ls -Altr
      - name: Simple JS Action
        id: greet #! ..................................... note_0001
        uses: actions/hello-world-javascript-action@e76147da8e5c81eaf017dede5645551d4b94427b
        with:
          who-to-greet: John
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}" #!.... note_0002

# note_0001: 他所から steps.greet でアクセスできるようにする
# note_0002: ステップ「steps.greet」の出力結果(outputs)は、変数「time」に格納されている.
#            <https://github.com/actions/hello-world-javascript-action#hello-world-javascript-action>
# note_0003: matches feature/featA, feature/featB, doesn't match feature/feat/a
# note_0004: matches feature/featA, feature/featB, feature/feat/a
