name: Shell Commands #! the name of our entire workflow (02:21)

on: [push]

jobs:
  run-shell-command: #! note_0001
    runs-on: ubuntu-latest
    timeout-minutes: 1 #! 1分でタイムアウトとする
    steps: 
      - name: echo a string
        run: |
          sleep 120    #! 2分待機する
          echo "Hello World"
        timeout-minutes: 0
        continue-on-error: false
      - name: multiline script 
        run: |
           node -v 
           npm -v
           python --version
      - name: python Command 
        run: |
          import platform 
          print(platform.processor())
        shell: python
  run-windwos-commands:
    runs-on: windows-latest
    needs: ["run-shell-command"] #! 上述の「note_0001」の終了後に実行する
    steps:
      - name: Directory PowerShell
        run: Get-Location 
      - name: Directory Bash 
        run: pwd 
        shell: bash 
